// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpnucjcvxnapprpijqhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wbnVjamN2eG5hcHBycGlqcWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzgzMTksImV4cCI6MjA1OTc1NDMxOX0.fZ3aVjLbn2zlF8r8HVDeSeqwV-ec52XnV7Hbtz4YuOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);